[filetype]
rules = [
    # Symbolic links
    { url = "*", is = "link", fg = "cyan" },
    { url = "*", is = "orphan", fg = "red" },
    
    # Executables
    { url = "*", is = "exec", fg = "green" },
    
    # Images
    { mime = "image/*", fg = "yellow" },
    # Videos
    { mime = "video/*", fg = "magenta" },
    { mime = "audio/*", fg = "magenta" },
    # Empty files
    { mime = "inode/empty", fg = "darkgray" },
    
    # Archives
    { url = "*zip", fg = "#FFA500" },
    { url = "*rar", fg = "#FFA500" },
    { mime = "application/xz", fg = "#FFA500" },
    { mime = "application/bz", fg = "#FFA500" },
    { mime = "application/bz2", fg = "#FFA500" },
    { mime = "application/7z-compressed", fg = "#FFA500" },
    { mime = "application/tar", fg = "#FFA500" },
    { mime = "application/gzip", fg = "#FFA500" },
    { mime = "application/zstd", fg = "#FFA500" },
    
    # Directories
    { url = "*/", fg = "blue" },
    { url = "*/", is = "link", fg = "cyan" },
    { url = "*/", is = "hidden", fg = "#0F7CB0", dim = true },
]
[icon]
exts = [
	{ name = "iso", text = "ðŸ’½", fg = "#00afff" },
	{ name = "bin", text = "ðŸ“€", fg = "#00afff" },
	{ name = "img", text = "ðŸ“€", fg = "#00afff" },
	{ name = "mdf", text = "ðŸ“€", fg = "#00afff" },
	{ name = "nrg", text = "ðŸ“€", fg = "#00afff" },
]
